### ISSUE TITLE
Unhandled rejection SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by bintang007** [HCTools/HCDrill-tg#1] opened 2020-12-05 10:35 UTC
![Screenshot from 2020-12-05 17-34-20](https://user-images.githubusercontent.com/25783133/101240190-4883a400-3720-11eb-84ea-15909ade01a9.png)

**Comment by PANCHO7532** [comment] 2020-12-07 20:41
This is an error caused by the design of the code on how it attempts to decrypt module by module.
Already investigating this and probably a fix will be released in the next days

**Comment by PANCHO7532** [comment] 2021-01-20 08:35
Fixed in the latest update

**Closed by PANCHO7532** 2021-01-20 08:35 UTC
Labels: bug
